import { PortfolioItemModel } from "@/models";
import { connectDB } from "@/lib/db";
import { getAuth,can } from "@/lib/rbac";
import { ok,fail } from "@/lib/api";
import { sanitizeLocalizedHtml } from "@/lib/sanitize";
import { z } from "zod";
import { createContentRevision } from "@/lib/revisions";
import { seoInput } from "@/lib/validators";
import { createContentRevision } from "@/lib/revisions";
const localized=z.object({fa:z.string().max(5000).optional(),en:z.string().max(5000).optional()});
const text=z.object({fa:z.string().max(100000).optional(),en:z.string().max(100000).optional()});
const input=z.object({slug:z.string().trim().min(1).max(160),title:localized,description:text.optional(),treatment:text.optional(),categoryIds:z.array(z.string()).optional(),beforeMediaIds:z.array(z.string()).optional(),afterMediaIds:z.array(z.string()).optional(),doctorId:z.string().nullable().optional(),privacy:z.object({consentStatus:z.enum(["unknown","granted","revoked"]).optional(),hideIdentity:z.boolean().optional()}).optional(),seo:seoInput.optional(),status:z.enum(["draft","published","scheduled","archived"]).optional(),publishedAt:z.coerce.date().nullable().optional(),scheduledAt:z.coerce.date().nullable().optional()}).partial();
function sanitizePortfolio(data:z.infer<typeof input>){return {...data,description:data.description?sanitizeLocalizedHtml(data.description):undefined,treatment:data.treatment?sanitizeLocalizedHtml(data.treatment):undefined};}
export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){const a=await getAuth(req);if(!a||!can(String(a.role),"content:read"))return fail("Forbidden",403);try{await connectDB();const {id}=await params;const item=await PortfolioItemModel.findById(id).lean();return item?ok(item):fail("Portfolio item not found",404);}catch(e){return fail(e instanceof Error?e.message:"Unable to load portfolio item",500);}}
export async function PUT(req:Request,{params}:{params:Promise<{id:string}>}){const a=await getAuth(req);if(!a||!can(String(a.role),"content:write"))return fail("Forbidden",403);try{const p=input.safeParse(await req.json());if(!p.success)return fail("Invalid portfolio payload",422,p.error.flatten());await connectDB();const {id}=await params;if(p.data.slug&&await PortfolioItemModel.exists({slug:p.data.slug,_id:{$ne:id}}))return fail("Slug already exists",409);const item=await PortfolioItemModel.findByIdAndUpdate(id,{$set:{...sanitizePortfolio(p.data),updatedBy:a.sub}},{new:true,runValidators:true}).lean();if(item)await createContentRevision("portfolio",id,item,String(a.sub),"update");return item?ok(item):fail("Portfolio item not found",404);}catch(e){return fail(e instanceof Error?e.message:"Update failed",500);}}
export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){const a=await getAuth(req);if(!a||!can(String(a.role),"content:write"))return fail("Forbidden",403);try{await connectDB();const {id}=await params;const item=await PortfolioItemModel.findByIdAndUpdate(id,{$set:{status:"archived",updatedBy:a.sub}},{new:true}).lean();return item?ok(item):fail("Portfolio item not found",404);}catch(e){return fail(e instanceof Error?e.message:"Archive failed",500);}}
