import {Schema,model,models} from "mongoose"; import {localizedStringSchema,localizedTextSchema,seoSchema,contentStatus,auditFields} from "./common";

const scheduleFields={publishedAt:Date,scheduledAt:Date};
const Doctor=new Schema({slug:{type:String,unique:true,index:true},name:localizedStringSchema,shortBio:localizedTextSchema,bio:localizedTextSchema,photoMediaId:{type:Schema.Types.ObjectId,ref:"Media"},cv:localizedTextSchema,university:localizedStringSchema,certificates:[{title:localizedStringSchema,issuer:localizedStringSchema,year:Number,mediaId:{type:Schema.Types.ObjectId,ref:"Media"}}],courses:[{title:localizedStringSchema,provider:localizedStringSchema,year:Number}],credentials:[{title:localizedStringSchema,description:localizedTextSchema}],services:[{type:Schema.Types.ObjectId,ref:"Service"}],status:contentStatus,seo:seoSchema,...scheduleFields,...auditFields},{timestamps:true});
const Service=new Schema({slug:{type:String,unique:true,index:true},title:localizedStringSchema,excerpt:localizedTextSchema,content:localizedTextSchema,suitableFor:localizedTextSchema,benefits:localizedTextSchema,limitations:localizedTextSchema,careInstructions:localizedTextSchema,faqs:[{question:localizedStringSchema,answer:localizedTextSchema}],icon:String,coverMediaId:{type:Schema.Types.ObjectId,ref:"Media"},bookingFee:{type:Number,min:0,default:0},currency:{type:String,default:"IRR"},status:contentStatus,seo:seoSchema,...scheduleFields,...auditFields},{timestamps:true});
const Page=new Schema({slug:{type:String,unique:true,index:true},title:localizedStringSchema,excerpt:localizedTextSchema,content:localizedTextSchema,status:contentStatus,seo:seoSchema,...scheduleFields,...auditFields},{timestamps:true});
const BlogCategory=new Schema({slug:{type:String,unique:true,index:true},name:localizedStringSchema,description:localizedTextSchema,seo:seoSchema,...auditFields},{timestamps:true});
const BlogPost=new Schema({slug:{type:String,unique:true,index:true},title:localizedStringSchema,excerpt:localizedTextSchema,content:localizedTextSchema,categoryIds:[{type:Schema.Types.ObjectId,ref:"BlogCategory"}],authorId:{type:Schema.Types.ObjectId,ref:"User"},coverMediaId:{type:Schema.Types.ObjectId,ref:"Media"},status:contentStatus,publishedAt:Date,scheduledAt:Date,seo:seoSchema,...auditFields},{timestamps:true});
const PortfolioCategory=new Schema({slug:{type:String,unique:true,index:true},name:localizedStringSchema,description:localizedTextSchema,seo:seoSchema,...auditFields},{timestamps:true});
const PortfolioPrivacy=new Schema({consentStatus:{type:String,enum:["unknown","granted","revoked"],default:"unknown"},hideIdentity:{type:Boolean,default:true}},{_id:false});
const PortfolioItem=new Schema({slug:{type:String,unique:true,index:true},title:localizedStringSchema,description:localizedTextSchema,treatment:localizedTextSchema,categoryIds:[{type:Schema.Types.ObjectId,ref:"PortfolioCategory"}],beforeMediaIds:[{type:Schema.Types.ObjectId,ref:"Media"}],afterMediaIds:[{type:Schema.Types.ObjectId,ref:"Media"}],doctorId:{type:Schema.Types.ObjectId,ref:"Doctor"},privacy:{type:PortfolioPrivacy,default:()=>({})},status:contentStatus,seo:seoSchema,...scheduleFields,...auditFields},{timestamps:true});

export const DoctorModel=models.Doctor||model("Doctor",Doctor); export const ServiceModel=models.Service||model("Service",Service); export const PageModel=models.Page||model("Page",Page); export const BlogCategoryModel=models.BlogCategory||model("BlogCategory",BlogCategory); export const BlogPostModel=models.BlogPost||model("BlogPost",BlogPost); export const PortfolioCategoryModel=models.PortfolioCategory||model("PortfolioCategory",PortfolioCategory); export const PortfolioItemModel=models.PortfolioItem||model("PortfolioItem",PortfolioItem);