import { DoctorModel } from "@/models";
import { connectDB } from "@/lib/db";
import { getAuth,can } from "@/lib/rbac";
import { ok,fail } from "@/lib/api";
import { z } from "zod";
const localized=z.object({fa:z.string().max(5000).optional(),en:z.string().max(5000).optional()});
const input=z.object({slug:z.string().trim().min(1).max(160),name:localized,shortBio:localized.optional(),bio:localized.optional(),photoMediaId:z.string().nullable().optional(),cv:localized.optional(),university:localized.optional(),certificates:z.array(z.any()).optional(),courses:z.array(z.any()).optional(),credentials:z.array(z.any()).optional(),services:z.array(z.string()).optional(),status:z.enum(["draft","published","scheduled","archived"]).optional()}).partial();
export async function PUT(req:Request,{params}:{params:Promise<{id:string}>}){const auth=await getAuth(req);if(!auth||!can(String(auth.role),"content:write"))return fail("Forbidden",403);try{const p=input.safeParse(await req.json());if(!p.success)return fail("Invalid doctor payload",422,p.error.flatten());await connectDB();const {id}=await params;if(p.data.slug&&await DoctorModel.exists({slug:p.data.slug,_id:{$ne:id}}))return fail("Slug already exists",409);const item=await DoctorModel.findByIdAndUpdate(id,{$set:{...p.data,updatedBy:auth.sub}},{new:true,runValidators:true}).lean();return item?ok(item):fail("Doctor not found",404);}catch(e){return fail(e instanceof Error?e.message:"Update failed",500);}}
export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){const auth=await getAuth(req);if(!auth||!can(String(auth.role),"content:write"))return fail("Forbidden",403);await connectDB();const {id}=await params;const item=await DoctorModel.findByIdAndUpdate(id,{$set:{status:"archived",updatedBy:auth.sub}},{new:true}).lean();return item?ok(item):fail("Doctor not found",404);}
